[package]
name = "nom"
version = "0.1.0"
authors = ["iosmanthus <myosmanthustree@gmail.com>"]
edition = "2018"

[dependencies]
nom = { git = "https://github.com/iosmanthus/nom.git", branch = "fix-cond-reduce" }
